project_id = "qetbvgvdsgetkkupbbse"

[functions.auth-login]
verify_jwt = false

[functions.auth-verify]
verify_jwt = false

[functions.credits-deduct]
verify_jwt = false

[functions.admin-passwords]
verify_jwt = false

[functions.aadhar-search]
verify_jwt = false

[functions.numinfo-v2]
verify_jwt = false

[functions.telegram-osint]
verify_jwt = false

[functions.call-dark]
verify_jwt = false

[functions.hit-api]
verify_jwt = false

[functions.execute-scheduled-hits]
verify_jwt = false
